start_epoch: 0
epochs: 200

# number of validation steps to execute at the beginning of the training
# num_sanity_val_steps: 0
trainer: "ortho_fix_train"
init_ddp: True

# ckpt path
resume_from_checkpoint: null

criterion:
  _target_: torch.nn.CrossEntropyLoss
  # label_smoothing: 0.1

lr: 0.01
lr_schedule:
  _target_: torch.optim.lr_scheduler.StepLR # torch.optim.lr_scheduler.CosineAnnealingLR
  _partial_: True
  step_size: 300
  gamma: 0.1
  # T_max: 25
lr_warmup: #null
  _target_: pytorch_warmup.LinearWarmup
  _partial_: True
  warmup_period: 100

lr_warmup_step_frequency: "epoch"
lr_warmup_step_args: null

optimizer:
  # _target_: torch.optim.SGD
  # _partial_: True
  # momentum: 0.9
  # weight_decay: 1.0e-5
  # nesterov: True
  _target_: torch.optim.Adam
  _partial_: True
  # _target_: torch.optim.RAdam
  # _partial_: True

init_opt_with_model: False
print_freq: 10

fixing_method:
  _target_: madonna.models.QROrthoFixingModel
  _partial_: True
  stability_frequency: 20
  delay: 50
  qthreshold: 0.99
  triu_fixed: True
  ortho_q_enforced: False
